/**
 * 389. Find the Difference
 * {@link https://leetcode.com/problems/find-the-difference/ | Link}
 *
 * Topics: Hash Table | String | Bit Manipulation | Sorting
 *
 * You are given two strings s and t.
 * String t is generated by random shuffling string s and then add one more letter at a random position.
 * Return the letter that was added to t.
 */
export function findTheDifference(s: string, t: string): string {
	let charCode = 0

	for (const ch of s) {
		charCode ^= ch.charCodeAt(0)
	}

	for (const ch of t) {
		charCode ^= ch.charCodeAt(0)
	}

	return String.fromCharCode(charCode)
}
